version: '3'

services:
  django:
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: {{ cookiecutter.project_slug }}_local_django
    volumes:
      - .:/app
    environment:
      - USE_DOCKER=yes
    ports:
      - "8000:8000"
    command: /start
